"""initial_schema

Revision ID: 795a09c3c7de
Revises: 
Create Date: 2026-09-19 14:50:39.867564
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '795a09c3c7de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('rq_job_id', sa.String(length=64), nullable=True))
    op.add_column('uploaded_images', sa.Column('pixel_size_m', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_number')
    op.drop_column('uploaded_images', 'pixel_size_m')
    op.drop_column('analyses', 'rq_job_id')
    # ### end Alembic commands ###
